language: go

install:
 - go get golang.org/x/tools/cmd/cover
 - go get github.com/mattn/goveralls

go:
 - 1.7
 - tip

script:
 - ./testandcover.bash
 - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken SPA43rgBqEwYyMuwfp9jf9OSXm3YtydUZ

